# Generated by Django 5.0.2 on 2025-05-19 15:02

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=100, verbose_name='Author Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Author Image')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestimonyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='testimonials.testimony')),
            ],
            options={
                'verbose_name': 'Testimony Translation',
                'db_table': 'testimonials_testimony_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
